### PR TITLE
Updated Payements and tasks for Kotlin contributors

### PR DESCRIPTION
**Pull request by adarshkr01**

### CODE REVIEW

**Review by odetolataiwo — COMMENTED** [review]
@Niekon01 please take a look the date.
Use a "/" instead of "-"

**Comment by adarshkr01** [comment]
I fixed and standardized all the dates the way I saw Bucky doing it. Please take a look.

**Comment by odetolataiwo** [comment]
can you take a look at the conflicts?

**Comment by adarshkr01** [comment]
I have resolved conflicts @odetolataiwo

**Pull request merged**
